import CompanyPage from "../components/Pages/CompanyPage/CompanyPage";
import ItemCreate from "../components/Pages/CreatePage/ItemCreate";
import PortfolioCreate from "../components/Pages/CreatePage/PortfolioCreate";
import FeedPage from "../components/Pages/FeedPage/FeedPage";
import ItemPage from "../components/Pages/ItemPage/ItemPage";
import LikePage from "../components/Pages/LikePage/LikePage";
import PlannerPage from "../components/Pages/PlannerPage/PlannerPage";
import SettingPage from "../components/Pages/SettingPage/SettingPage";
import PortfolioPage from "../components/Pages/PortfolioPage/PortfolioPage";
import RegistPage from "../components/Pages/RegistPage/RegistPage";
import SearchPage from "../components/Pages/SearchPage/SearchPage";
import Auth from "./auth";

export const AuthFeedPage = Auth(FeedPage, "all");
export const AuthItemPage = Auth(ItemPage, "customer");
export const AuthPlannerPage = Auth(PlannerPage, "customer");
export const AuthPortfolioPage = Auth(PortfolioPage, "customer");
export const AuthSearchPage = Auth(SearchPage, "customer");
export const AuthRegisterPage = Auth(RegistPage, "unregistered");
export const AuthItemCreate = Auth(ItemCreate, "all");
export const AuthPortfolioCreate = Auth(PortfolioCreate, "all");
export const AuthPlannerMyPage = Auth(PlannerPage, "all");
export const AuthLikePage = Auth(LikePage, "all");
export const AuthCompanyPage = Auth(CompanyPage, "all");
export const AuthSettingPage = Auth(SettingPage, "all");
